# DEV Compose file.
# For a production file see: README.md

version: '3.7'

services:
  memcached:
    image: memcached:1-alpine
    restart: unless-stopped
    entrypoint: memcached -m 256M -I 128M
    ports:
      - 11211:11211

  app:
    build: .
    depends_on:
      - memcached
    environment:
      SIZE_LIMIT: 128M
    ports:
      - 80:5000
