# DEV Compose file.
# For a production file see: README.md

version: '3.7'

services:
  memcached:
    image: memcached:1-alpine
    entrypoint: memcached -m 128
    ports:
      - 11211:11211

  app:
    build: .
    depends_on:
      - memcached
    ports:
      - 5000:5000
