name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build docker image
        run: npm run test:prepare

      - name: Prepare
        run: |
          npm install playwright
          npx playwright install --with-deps

      - name: Run your tests
        run: npm test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: test-results
