name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      # Docker
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Prepare
        run: |
          pnpm install --frozen-lockfile
          pnpm exec playwright install --with-deps
          pnpm run test:prepare

      - name: Run your tests
        run: pnpm test
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results
