name: test

on:
  workflow_dispatch:
  push:

jobs:
  text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          docker-compose build
          npm ci
      - name: Test
        run: npm run test:run
